"""empty message

Revision ID: 0b8dc0505d0b
Revises: cecb04c85dc5
Create Date: 2017-12-07 16:44:15.692012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8dc0505d0b'
down_revision = 'cecb04c85dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.drop_constraint('food_name_id_fkey', 'food', type_='foreignkey')
    op.create_foreign_key(None, 'food', 'users', ['recipient_id'], ['id'])
    op.drop_column('food', 'name_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('name_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'food', type_='foreignkey')
    op.create_foreign_key('food_name_id_fkey', 'food', 'users', ['name_id'], ['id'])
    op.drop_column('food', 'recipient_id')
    # ### end Alembic commands ###
