"""empty message

Revision ID: 9118020a3d21
Revises:
Create Date: 2017-12-12 10:52:51.629519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9118020a3d21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('patty', sa.Integer(), nullable=True),
    sa.Column('no_bun', sa.Boolean(), nullable=True),
    sa.Column('cheese', sa.Boolean(), nullable=True),
    sa.Column('bacon', sa.Boolean(), nullable=True),
    sa.Column('addons', sa.String(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('foods')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('addons', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name='foods_recipient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='foods_pkey')
    )
    op.drop_table('orders')
    # ### end Alembic commands ###
